#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Type checking
yarn lint:ts
echo "Type checking performed successfully: No errors found."

# Linting
yarn lint
echo "Linting performed successfully: No errors found."